In [17]:
file_path = DATA_PATH + "/Wearable_Dataset/ANAEROBIC/S05/ACC.csv"

with open(file_path, "r") as f:
    reader = csv.reader(f)

    for i, row in enumerate(reader):
        print(f"Row {i}:")
        print(row[:10])

        if i >= 5:
            break

Row 0:
['2013-02-23 12:43:28', '2013-02-23 12:43:28', '2013-02-23 12:43:28']
Row 1:
['32.0', '32.0', '32.0']
Row 2:
['41.0', '32.0', '38.0']
Row 3:
['43.0', '30.0', '37.0']
Row 4:
['42.0', '30.0', '39.0']
Row 5:
['45.0', '33.0', '34.0']

In [16]:
import csv

file_path = DATA_PATH + "/Wearable_Dataset/ANAEROBIC/S05/HR.csv"

with open(file_path, "r") as f:
    reader = csv.reader(f)

    for i, row in enumerate(reader):
        print(f"Row {i}:")
        print(row[:10])

        if i >= 5:
            break

Row 0:
['2013-02-23 12:43:38']
Row 1:
['1.0']
Row 2:
['48.0']
Row 3:
['57.0']
Row 4:
['74.33']
Row 5:
['79.0']

In [15]:
subject_path = DATA_PATH + "/Wearable_Dataset/ANAEROBIC/S05"

hr = pd.read_csv(subject_path + "/HR.csv")
eda = pd.read_csv(subject_path + "/EDA.csv")
temp = pd.read_csv(subject_path + "/TEMP.csv")
acc = pd.read_csv(subject_path + "/ACC.csv")
bvp = pd.read_csv(subject_path + "/BVP.csv")
ibi = pd.read_csv(subject_path + "/IBI.csv")

print("HR:")
display(hr.head())

print("EDA:")
display(eda.head())

print("TEMP:")
display(temp.head())

print("ACC:")
display(acc.head())

HR:

   2013-02-23 12:43:38
0                 1.00
1                48.00
2                57.00
3                74.33
4                79.00

EDA:

   2013-02-23 12:43:28
0             4.000000
1             0.000000
2             0.836457
3             1.183860
4             1.392723

TEMP:

   2013-02-23 12:43:28
0                 4.00
1               208.95
2               208.95
3               208.95
4               208.95

ACC:

   2013-02-23 12:43:28  2013-02-23 12:43:28.1  2013-02-23 12:43:28.2
0                 32.0                   32.0                   32.0
1                 41.0                   32.0                   38.0
2                 43.0                   30.0                   37.0
3                 42.0                   30.0                   39.0
4                 45.0                   33.0                   34.0

In [14]:
stress_v1 = pd.read_csv(DATA_PATH + "/Stress_Level_v1.csv")
stress_v2 = pd.read_csv(DATA_PATH + "/Stress_Level_v2.csv")

print("Stress v1:")
print(stress_v1.shape)
display(stress_v1.head())

print("\nStress v2:")
print(stress_v2.shape)
display(stress_v2.head())

print("V1 columns:")
print(stress_v1.columns.tolist())

print("\nV2 columns:")
print(stress_v2.columns.tolist())

print("V1 unique values:")
for col in stress_v1.columns:
    print(col, ":", stress_v1[col].unique()[:20])

print("\nV2 unique values:")
for col in stress_v2.columns:
    print(col, ":", stress_v2[col].unique()[:20])

Stress v1:
(18, 9)

,Unnamed: 0,Baseline,Stroop,First Rest,TMCT,Second Rest,Real Opinion,Opposite Opinion,Subtract
0,S01,3.0,4.5,4.0,4.0,5.5,6.0,7.0,7.0
1,S02,2.0,4.0,2.0,2.0,2.0,4.0,5.0,4.0
2,S03,3.0,3.0,3.0,4.0,3.0,3.0,3.0,3.0
3,S04,3.0,3.0,2.0,3.0,1.0,1.0,1.0,1.0
4,S05,1.0,2.0,1.0,4.0,1.0,2.0,2.0,3.0

Stress v2:
(18, 8)

,Unnamed: 0,Baseline,TMCT,First Rest,Real Opinion,Opposite Opinion,Second Rest,Subtract
0,f01,2.0,5.0,2.0,3.0,4.0,2.0,3.0
1,f02,3.0,5.0,1.0,2.0,3.0,2.0,3.0
2,f03,5.0,8.0,1.0,3.0,5.0,1.0,6.0
3,f04,2.0,4.0,3.0,3.0,4.0,1.0,4.0
4,f05,3.0,4.0,3.0,3.0,3.0,2.0,3.0

V1 columns:
['Unnamed: 0', 'Baseline', 'Stroop', 'First Rest', 'TMCT', 'Second Rest', 'Real Opinion', 'Opposite Opinion', 'Subtract']

V2 columns:
['Unnamed: 0', 'Baseline', 'TMCT', 'First Rest', 'Real Opinion', 'Opposite Opinion', 'Second Rest', 'Subtract']
V1 unique values:
Unnamed: 0 : <StringArray>
['S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11',
 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18']
Length: 18, dtype: str
Baseline : [3. 2. 1. 5. 0. 7. 4. 6.]
Stroop : [4.5 4.  3.  2.  6.  1.  5.  8. ]
First Rest : [4. 2. 3. 1. 6. 5.]
TMCT : [4.  2.  3.  5.  8.  5.5 6.  9.  7. ]
Second Rest : [5.5 2.  3.  1.  7.  1.5 4.  5.  6. ]
Real Opinion : [6.  4.  3.  1.  2.  8.  0.5 7.  5. ]
Opposite Opinion : [7.  5.  3.  1.  2.  9.  0.5 6.  4. ]
Subtract : [7.  4.  3.  1.  5.  9.  1.5 2. ]

V2 unique values:
Unnamed: 0 : <StringArray>
['f01', 'f02', 'f03', 'f04', 'f05', 'f06', 'f07', 'f08', 'f09', 'f10', 'f11',
 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18']
Length: 18, dtype: str
Baseline : [2. 3. 5. 1. 0. 6. 4. 7.]
TMCT : [ 5.  8.  4.  3.  6.  9.  7. 10.]
First Rest : [2. 1. 3. 5. 4. 6.]
Real Opinion : [3. 2. 1. 4. 5. 6.]
Opposite Opinion : [4. 3. 5. 1. 7. 6.]
Second Rest : [2. 1. 3. 4. 6.]
Subtract : [3. 6. 4. 2. 5. 9.]

In [11]:
subject_path = DATA_PATH + "/subject-info.csv"

subjects = pd.read_csv(subject_path)

print("Shape:", subjects.shape)

display(subjects.head())

print("\nColumns:")
print(subjects.columns.tolist())

print("\nMissing values:")
display(subjects.isnull().sum())

Shape: (46, 10)

,Info,Gender,Age,Height (cm),Weight (kg),Does physical activity regularly?,Protocol,Stress Inducement,Aerobic Exercise,Anaerobic Exercise
0,S01,m,21,192,84,Yes,V1,Yes,Yes,Yes****
1,S02,m,20,185,95,No,V1,Yes****,Yes,Yes
2,S03,m,20,175,62,Yes,V1,Yes,Yes***,Yes
3,S04,m,21,174,70,Yes,V1,Yes,Yes,Yes
4,S05,m,21,173,72,Yes,V1,Yes,Yes,Yes

Columns:
['Info ', 'Gender', 'Age', 'Height (cm)', 'Weight (kg)', 'Does physical activity regularly?', 'Protocol', 'Stress Inducement', 'Aerobic Exercise', 'Anaerobic Exercise']

Missing values:

Info                                  1
Gender                               10
Age                                  10
Height (cm)                          10
Weight (kg)                          10
Does physical activity regularly?    10
Protocol                             10
Stress Inducement                    10
Aerobic Exercise                     10
Anaerobic Exercise                   10
dtype: int64

In [7]:
DATA_PATH = "../data/raw/wearable"

dictionary_path = DATA_PATH + "/Data_Dictionary.csv"

data_dictionary = pd.read_csv(dictionary_path,encoding="latin1")

print(data_dictionary.shape)
display(data_dictionary)

(7, 5)

,Code,Variable Name,Description,Sampling Frequency (Hz),Units
0,EDA,Electrodermal Activity,Data from the electrodermal activity sensor,4,microsiemens (uS)
1,TEMP,Skin Temperature,Data from temperature sensor,4,Celsius (°C)
2,BVP,Blood Volume Pulse,Data from photoplethysmograph,64,-
3,HR,Heart Rate,Average heart rate extracted from the BVP signal,1,beats per minute (BPM)
4,IBI,Inter Beat Interval,Time between individuals heart beats extracted...,-,-
5,ACC,3-axis Accelerometer,Data from 3-axis accelerometer sensor (x;y;z),32,1/64g
6,tags,Event mark times,Each mark corresponds to a physical button pre...,-,-

In [5]:
import os

DATA_PATH = "../data/raw/wearable"

for root, dirs, files in os.walk(DATA_PATH):
    level = root.replace(DATA_PATH, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")
    
    for file in files[:10]:
        print(f"{indent}    {file}")

wearable/
    Wearable_Dataset.ipynb
    Stress_Level_v2.csv
    subject-info.csv
    data_constraints.txt
    Stress_Level_v1.csv
    README.txt
    LICENSE.txt
    Data_Dictionary.csv
    SHA256SUMS.txt
    Wearable_Dataset/
        ANAEROBIC/
            S05/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S02/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f11/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f10/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S03/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S04/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S16_a/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f03/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f04/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S17/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S10/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S11/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f05/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f02/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S18/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S01/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S06/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S08/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f12/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S09/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f13/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S07/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S16_b/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f07/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S13/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f09/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S14/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S15/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S12/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f08/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f01/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f06/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
        AEROBIC/
            S05/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S02/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f11/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f10/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S03/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S04/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f03/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f04/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S17/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S10/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S11_a/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S16/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f05/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f02/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S18/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S01/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S06/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S08/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f12/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S09/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f13/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S07/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f07/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S13/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f09/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S14/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S11_b/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S15/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f08/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f01/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f06/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
        STRESS/
            S05/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f18/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S02/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f11/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f16/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f17/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f10/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S03/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S04/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f14_b/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f03/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f04/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S17/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S10/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S11/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S16/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f05/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f02/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S18/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S01/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S06/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f15/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S08/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f12/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S09/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f13/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S07/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f14_a/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f07/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S13/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f09/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S14/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S15/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            S12/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f08/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f01/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv
            f06/
                TEMP.csv
                tags.csv
                HR.csv
                ACC.csv
                IBI.csv
                EDA.csv
                BVP.csv